//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURRENT_STATUS()
        {
            this.STATUS_REASON = new HashSet<STATUS_REASON>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_COMPLECT { get; set; }
        public decimal ID_STATUS { get; set; }
        public System.DateTime DATE_STATUS { get; set; }
    
        public virtual COMPONENT COMPONENT { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATUS_REASON> STATUS_REASON { get; set; }
    }
}
