//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURRENT_STATUS()
        {
            this.COMPONENT = new HashSet<COMPONENT>();
        }
    
        public decimal ID_SERIES { get; set; }
        public Nullable<decimal> ID_STATUS { get; set; }
        public Nullable<System.DateTime> DATE_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPONENT> COMPONENT { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
