//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPONENT> COMPONENT { get; set; }
        public virtual DbSet<CURRENT_STATUS> CURRENT_STATUS { get; set; }
        public virtual DbSet<MODEL> MODEL { get; set; }
        public virtual DbSet<PRICE> PRICE { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<STATUS_REASON> STATUS_REASON { get; set; }
        public virtual DbSet<TYPE> TYPE { get; set; }
    }
}
