//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE
    {
        public decimal ID { get; set; }
        public decimal ID_MODEL { get; set; }
        public Nullable<System.DateTime> DATE_ADD { get; set; }
        public decimal PRICE1 { get; set; }
    
        public virtual MODEL MODEL { get; set; }
    }
}
